"""
Phase 5: Neuro-Symbolic Gap Analysis

This is the neuro-symbolic core of the pipeline

Symbolic component (input):
    The SHACL conformance report from Phase 4 encodes HI principle violations
    as formal symbolic structures. Each violation maps a specific KG node
    against a CARE-principle constraint derived from the HI Ontology:
        - Which ontology class failed (hi:Interaction, hi:HITeam, etc.)
        - Which CARE dimension was violated (Collaborative, Adaptive, ...)
        - Which specific constraint was not satisfied (qualifiedMinCount,
          minCount on a required property, SPARQL text check, etc.)
        - Severity: sh:Violation (hard fail) or sh:Warning (soft gap)

Neural component (reasoning):
    A large language model (GPT-4o-mini by default) receives these symbolic
    violations as structured input and performs semantic reasoning to produce:
        - A precise gap title and description
        - The HI principle that is unmet
        - The practical real-world impact on human-AI collaboration
        - A severity assessment (Critical / Major / Minor)

The LLM does NOT generate descriptions from a feature list. It reasons about formal SHACL symbolic constraint violations
in the context of HI theory this is the neuro-symbolic design: 
the symbolic layer surfaces the gaps, the neural layer explains their significance.

Setup:
    export OPENAI_API_KEY="sk-..."
    # or add OPENAI_API_KEY to a .env file in the project root

Configuration:
    LLM model defaults to gpt-4o-mini. Override by setting LLM_MODEL in the
    environment or adding 'llm_model' to your YAML config
terminal:
    from pipeline.phase5_gap_analysis.gap_analyzer import run
    run(config)
"""

import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from pipeline.config import Config
from pipeline.metrics import write_metrics
from openai import OpenAI, APIError, RateLimitError, APITimeoutError


DEFAULT_MODEL    = "gpt-4o-mini"
MAX_RETRIES      = 3
RETRY_DELAY_SEC  = 5
TEMPERATURE      = 0.2   # low temperature for analytical, consistent output

# CARE dimension definitions injected into every LLM call as grounding, the text was generated by llm as I already am familiar with them
CARE_DEFINITIONS = {
    "Collaborative": (
        "Human and AI agents actively work TOGETHER — both must be present and "
        "explicitly participating in interactions and task executions. "
        "Collaboration is not achieved if the AI only produces output that humans "
        "act on separately; both must be co-participants in the same episode."
    ),
    "Adaptive": (
        "The system learns and improves over time through feedback loops. "
        "Human actions (accept, reject, refine) feed back into model updates. "
        "Preferences persist across sessions. The system reduces cognitive burden "
        "on humans by accumulating knowledge from prior interactions."
    ),
    "Responsible": (
        "Human oversight, fairness, and accountability are embedded in the design. "
        "Humans retain final decision authority. Fairness mechanisms prevent "
        "discriminatory outcomes. Decision points are explicit and auditable. "
        "No consequential action is taken autonomously without human approval."
    ),
    "Explainable": (
        "The AI can explain its decisions, recommendations, and reasoning to human "
        "agents in understandable terms. Match/gap indicators, evidence citations, "
        "filter breakdowns, or other transparency mechanisms allow humans to "
        "understand and verify AI outputs before acting on them."
    ),
}

# Mapping RDF class name fragments to human readable descriptions
NODE_TYPE_LABELS = {
    "Interaction":    "hi:Interaction (a recorded human-AI interaction episode)",
    "HITeam":         "hi:HITeam (the human-AI team for this scenario)",
    "Goal":           "hi:Goal (the shared team goal)",
    "TaskExecution":  "hi:TaskExecution (a task performed by the team)",
    "Evaluation":     "hi:Evaluation (the assessment of task outcomes)",
    "Task":           "hi:Task (a task requiring specific capabilities)",
}



# Symbolic input preparation

def _node_type_from_uri(focus_uri: str) -> str:
    # in this function I Infer the ontology class of a KG node from its URI pattern
    for fragment, label in NODE_TYPE_LABELS.items():
        if f"/{fragment}/" in focus_uri:
            return label
    return "unknown KG node"


def _format_violation_block(violation: dict, index: int) -> str:
    """
    In this functiin I format a single SHACL violation as structured text for the LLM prompt

    The text preserves the symbolic nature of the violation so the LLM
    reasons about formal constraint failures, not just natural language
    """
    severity_note = (
        "MUST FIX — a required HI property is entirely absent"
        if violation["severity"] == "Violation"
        else "IMPROVEMENT — an HI property is present but weak or implicit"
    )
    node_type = _node_type_from_uri(violation.get("focus_node", ""))

    lines = [
        f"[Violation {index}]",
        f"  CARE Dimension   : {violation.get('care_dim', 'General')}",
        f"  Severity         : sh:{violation['severity']} — {severity_note}",
        f"  Component        : {violation['component']}",
        f"  Failed node type : {node_type}",
        f"  Constraint msg   : {violation['message']}",
    ]
    return "\n".join(lines)


def _build_violation_context(scenario_data: dict) -> str:
    violations = scenario_data.get("violations", [])
    if not violations:
        return "No violations detected"

    blocks = []
    for i, v in enumerate(violations, 1):
        blocks.append(_format_violation_block(v, i))
    return "\n\n".join(blocks)


def _build_care_context() -> str:
    # the CARE principle definitions block for the system prompt
    lines = ["CARE PRINCIPLE DEFINITIONS (from HI Ontology, VU Amsterdam):"] 
    for dim, defn in CARE_DEFINITIONS.items():
        lines.append(f"\n  {dim}:\n    {defn}")
    return "\n".join(lines)



# LLM prompts

SYSTEM_PROMPT = f"""You are a Hybrid Intelligence (HI) systems analyst specialising in the CARE framework and the HI Ontology developed at VU Amsterdam.

{_build_care_context()}

You receive SHACL constraint violations from a Knowledge Graph that formally models a real-world AI system against the HI Ontology. These violations are symbolic — each one encodes a specific, formal constraint failure against a CARE principle.

Your task is to interpret these symbolic constraint violations and produce a structured gap analysis. You are performing neuro-symbolic reasoning: the symbolic layer has already identified WHAT is missing; you must explain WHY it matters and assess its significance for the human-AI collaborative system.

Rules:
- Be precise and analytical, not generic.
- Each gap must reference the specific violation it interprets.
- Severity: Critical = fundamental HI property absent (the system cannot be called HI without it); Major = significant gap with real impact on collaboration quality; Minor = improvement area that does not fundamentally break HI.
- Do not add gaps not grounded in the violations provided.
- Respond with valid JSON only — no markdown, no explanation outside the JSON."""


def _build_user_prompt(usecase: str, sc_id: str, label: str,
                       status: str, violation_context: str) -> str:
    """Build the per-scenario user prompt for the LLM"""
    sc_upper = sc_id.upper()
    return f"""Interpret the following SHACL violations for scenario '{label}' in the '{usecase}' AI system assessment.

## Scenario
- ID: {sc_upper}
- Label: {label}
- Use Case: {usecase}
- HI Conformance Status: {status}

## Symbolic SHACL Violations
{violation_context}

## Output Schema
Return a single JSON object exactly matching this structure:

{{
  "scenario_id": "{sc_upper}",
  "overall_assessment": "<1-2 sentence assessment of this scenario's HI conformance — what works and what is missing>",
  "gaps": [
    {{
      "gap_id": "G-{sc_upper}-01",
      "care_dimension": "<Collaborative|Adaptive|Responsible|Explainable>",
      "severity": "<Critical|Major|Minor>",
      "component": "<exact component name from violation>",
      "gap_title": "<concise title, max 10 words>",
      "gap_description": "<2-3 sentences: what is missing and why it matters for HI>",
      "hi_principle_violated": "<which specific HI/CARE principle from the ontology is unmet>",
      "practical_impact": "<1-2 sentences: real-world effect on human-AI collaboration quality>"
    }}
  ]
}}

Number gap_ids sequentially: G-{sc_upper}-01, G-{sc_upper}-02, etc.
One gap entry per violation. If multiple violations share the same CARE dimension and root cause, merge them into one gap and note both in the description."""



# LLM caller

def _call_llm(
    client: OpenAI,
    model: str,
    user_prompt: str,
    sc_label: str,
) -> Tuple[Optional[Dict[str, Any]], Optional[Dict[str, int]]]:

    # Call the LLM with retry logic and JSON response parsing

    # Returns (parsed JSON dict, token usage dict) on success, or
    # (None, usage-or-None) on failure. usage is returned even on a JSON
    # parse failure (the call still consumed tokens) but is None if no
    # response was ever received (rate limit / timeout / API error exhausted
    # all retries).

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                temperature=TEMPERATURE,
                max_tokens=1500,
            )
            usage = getattr(response, "usage", None)
            usage_dict = {
                "prompt_tokens":     getattr(usage, "prompt_tokens", 0) or 0,
                "completion_tokens": getattr(usage, "completion_tokens", 0) or 0,
            } if usage else {"prompt_tokens": 0, "completion_tokens": 0}

            raw = response.choices[0].message.content.strip()
            return json.loads(raw), usage_dict

        except RateLimitError:
            wait = RETRY_DELAY_SEC * attempt
            print(f"    [Rate limit] Waiting {wait}s before retry {attempt}/{MAX_RETRIES}...")
            time.sleep(wait)

        except APITimeoutError:
            print(f"    [Timeout] Retry {attempt}/{MAX_RETRIES}...")
            time.sleep(RETRY_DELAY_SEC)

        except APIError as e:
            print(f"    [API error] {e} — retry {attempt}/{MAX_RETRIES}...")
            time.sleep(RETRY_DELAY_SEC)

        except json.JSONDecodeError as e:
            print(f"    [JSON parse error] LLM response was not valid JSON: {e}")
            return None, usage_dict

    print(f"    [ERROR] Failed to get gap analysis for '{sc_label}' after {MAX_RETRIES} attempts.")
    return None, None



# Report builders

def _build_pass_entry(sc_id: str, label: str) -> Dict[str, Any]:
    # gap entry for a PASS scenario (no LLM call needed)
    return {
        "scenario_id": sc_id.upper(),
        "overall_assessment": (
            f"Scenario '{label}' satisfies all evaluated HI conformance constraints. "
            "All CARE dimensions (Collaborative, Adaptive, Responsible, Explainable) "
            "are structurally and semantically present in the KG."
        ),
        "gaps": [],
    }


def _care_gap_summary(scenario_results: Dict[str, Dict]) -> Dict[str, int]:
    # Count total hard-violation gaps per CARE dimension across all scenarios
    summary: Dict[str, int] = {
        "Collaborative": 0, "Adaptive": 0,
        "Responsible": 0, "Explainable": 0, "General": 0,
    }
    for sc_data in scenario_results.values():
        for gap in sc_data.get("gaps", []):
            dim = gap.get("care_dimension", "General")
            summary[dim] = summary.get(dim, 0) + 1
    return summary


def _severity_summary(scenario_results: Dict[str, Dict]) -> Dict[str, int]:
    # Count gaps by severity across all scenarios
    counts: Dict[str, int] = {"Critical": 0, "Major": 0, "Minor": 0}
    for sc_data in scenario_results.values():
        for gap in sc_data.get("gaps", []):
            sev = gap.get("severity", "Minor")
            counts[sev] = counts.get(sev, 0) + 1
    return counts


# terminal output

def run(config: Config) -> None:
    # Phase 5 entry point called by run_pipeline.py

    print("\n" + "=" * 62)
    print(f"  PHASE 5: Neuro-Symbolic Gap Analysis  |  {config.usecase.upper()}")
    print("=" * 62)

    # Verify Phase 4 has run
    if not config.shacl_report_path.exists():
        print(
            f"[Phase 5 ERROR] SHACL report not found: {config.shacl_report_path}\n"
            "  Run Phase 4 (SHACL Conformance Validation) first.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Load Phase 4 report
    print(f"[Phase 5] Loading SHACL report  : {config.shacl_report_path}")
    with open(config.shacl_report_path, "r", encoding="utf-8") as f:
        shacl_report = json.load(f)

    scenarios = shacl_report.get("scenarios", {})
    all_ids   = sorted(scenarios.keys())
    total     = len(all_ids)
    failing   = [sc for sc in all_ids
                 if scenarios[sc].get("status") in ("FAIL", "WARNING")]
    passing   = [sc for sc in all_ids if sc not in failing]

    print(f"[Phase 5] Scenarios loaded      : {total} total, "
          f"{len(failing)} with violations, {len(passing)} PASS")

    # Initialise OpenAI client
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        print(
            "\n[Phase 5 ERROR] OPENAI_API_KEY environment variable is not set.\n"
            "  Set it with: export OPENAI_API_KEY='sk-...'\n"
            "  Then re-run Phase 5.",
            file=sys.stderr,
        )
        sys.exit(1)

    model = os.environ.get("LLM_MODEL", DEFAULT_MODEL).strip()
    client = OpenAI(api_key=api_key)
    print(f"[Phase 5] LLM model             : {model}")
    print(f"[Phase 5] Method                : neuro-symbolic (SHACL → LLM reasoning)")
    print()

    # Process each scenario
    scenario_results: Dict[str, Dict] = {}

    # Performance tracking (see pipeline/metrics.py): how many scenarios
    # actually needed an LLM call, how often the symbolic fallback fired
    # instead of a successful LLM interpretation, and cumulative token usage.
    llm_calls_attempted  = 0
    fallback_count       = 0
    total_prompt_tokens  = 0
    total_completion_tokens = 0

    for sc_id in all_ids:
        sc_data = scenarios[sc_id]
        label   = sc_data.get("label", sc_id.upper())
        status  = sc_data.get("status", "PASS")

        if status == "PASS":
            print(f"  ✓ [{sc_id.upper()}] {label[:52]}  no gaps")
            scenario_results[sc_id] = _build_pass_entry(sc_id, label)
            continue

        # Build symbolic violation context
        violation_context = _build_violation_context(sc_data)
        user_prompt = _build_user_prompt(
            config.usecase, sc_id, label, status, violation_context
        )

        n_viols = sc_data.get("violation_count", 0)
        n_warns = sc_data.get("warning_count", 0)
        print(f"  ✗ [{sc_id.upper()}] {label[:48]}")
        print(f"      {n_viols} violation(s), {n_warns} warning(s) --> calling {model} ...")

        llm_calls_attempted += 1
        result, usage = _call_llm(client, model, user_prompt, label)

        if usage:
            total_prompt_tokens     += usage.get("prompt_tokens", 0)
            total_completion_tokens += usage.get("completion_tokens", 0)

        if result is None:
            # Fallback: build a minimal gap entry from the symbolic data alone
            fallback_count += 1
            print(f"      [FALLBACK] Using symbolic violations directly")
            result = _build_fallback_entry(sc_id, label, sc_data)

        scenario_results[sc_id] = result
        n_gaps = len(result.get("gaps", []))
        print(f"      → {n_gaps} gap(s) identified")

    # Assemble full report
    care_summary     = _care_gap_summary(scenario_results)
    severity_summary = _severity_summary(scenario_results)
    total_gaps       = sum(len(r.get("gaps", [])) for r in scenario_results.values())

    report = {
        "usecase":              config.usecase,
        "phase":                "5-gap-analysis",
        "method":               "neuro-symbolic",
        "llm_model":            model,
        "timestamp":            datetime.now(timezone.utc).isoformat(),
        "shacl_report_file":    str(config.shacl_report_path),
        "total_scenarios":      total,
        "scenarios_with_gaps":  len(failing),
        "total_gaps":           total_gaps,
        "care_gap_summary":     care_summary,
        "severity_summary":     severity_summary,
        "scenarios":            scenario_results,
    }

    # Write output
    with open(config.gap_analysis_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    print(f"\n[Phase 5] Gap analysis written  : {config.gap_analysis_path}")

    # Performance metrics: LLM call volume, fallback rate, and token cost.
    # A high fallback rate here is a direct "is this framework practically
    # usable" signal — it means the neuro-symbolic interpretation step is
    # failing and results are falling back to raw SHACL messages.
    write_metrics(config, 5, {
        "scenarios_total":            total,
        "scenarios_requiring_llm":    llm_calls_attempted,
        "llm_fallback_triggered":     fallback_count,
        "llm_fallback_rate":          (fallback_count / llm_calls_attempted) if llm_calls_attempted else 0.0,
        "total_prompt_tokens":        total_prompt_tokens,
        "total_completion_tokens":    total_completion_tokens,
        "total_tokens":               total_prompt_tokens + total_completion_tokens,
        "total_gaps":                 total_gaps,
    })

    # Print summary
    _print_summary(config.usecase, all_ids, scenarios, scenario_results,
                   care_summary, severity_summary, total_gaps)

    print("\n[Phase 5] Complete \n")

# this was recommended and written by llm
def _build_fallback_entry(sc_id: str, label: str,
                          sc_data: dict) -> Dict[str, Any]:
    """
    Construct a minimal gap entry directly from SHACL violation data,
    used when the LLM call fails. Preserves the symbolic structure.
    """
    gaps = []
    for i, v in enumerate(sc_data.get("violations", []), 1):
        gaps.append({
            "gap_id":              f"G-{sc_id.upper()}-{i:02d}",
            "care_dimension":      v.get("care_dim", "General"),
            "severity":            "Major" if v["severity"] == "Violation" else "Minor",
            "component":           v["component"],
            "gap_title":           v["component"],
            "gap_description":     v["message"],
            "hi_principle_violated": v.get("care_dim", "General"),
            "practical_impact":    "(LLM unavailable — see constraint message above)",
        })
    return {
        "scenario_id":       sc_id.upper(),
        "overall_assessment": f"[Fallback] {len(gaps)} SHACL violation(s) detected. LLM interpretation unavailable.",
        "gaps":              gaps,
    }


def _print_summary(
    usecase: str,
    all_ids: List[str],
    shacl_scenarios: Dict[str, Dict],
    scenario_results: Dict[str, Dict],
    care_summary: Dict[str, int],
    severity_summary: Dict[str, int],
    total_gaps: int,
) -> None:
    # Print the gap analysis summary to the terminal
    print(f"\n  Gap Analysis Summary — {usecase.upper()}")
    print(f"  {'─' * 55}")
    print(f"  Total gaps identified : {total_gaps}")
    print(f"  By severity           : "
          f"Critical={severity_summary.get('Critical',0)}  "
          f"Major={severity_summary.get('Major',0)}  "
          f"Minor={severity_summary.get('Minor',0)}")
    dims_with_gaps = {k: v for k, v in care_summary.items() if v > 0}
    if dims_with_gaps:
        print(f"  By CARE dimension     : "
              + "  ".join(f"{k[0]}={v}" for k, v in dims_with_gaps.items()))
    print(f"  {'─' * 55}")

    for sc_id in all_ids:
        result = scenario_results.get(sc_id, {})
        gaps   = result.get("gaps", [])
        icon   = "✓" if not gaps else "✗"
        # Get label from the Phase 4 SHACL report (more reliable than LLM response)
        label  = shacl_scenarios.get(sc_id, {}).get("label", sc_id.upper())
        print(f"  {icon} [{sc_id.upper()}] {label[:50]}")
        for g in gaps:
            sev_icon = "!!" if g.get("severity") == "Critical" else " !"
            print(f"        {sev_icon} [{g.get('care_dimension','?')}] "
                  f"[{g.get('severity','?')}] {g.get('gap_title','?')}")

    print(f"  {'─' * 55}")
    if total_gaps == 0:
        print("  ✓ No HI gaps identified, system fully conforms")
    else:
        print(f"  ✗ {total_gaps} gap(s) identified, ready for Phase 6 (Recommendations)")

